### ISSUE TITLE
Reconnection problem behind proxy (Windows)

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-c-shared-utility#131]
Hi,

I'm facing issues with the schannel version of tlsio when using the azure sdk.
When using a proxy and the device is disconnected, the reconnection is never back on, but instead I have the following error:
```
[13:55:08.820][ERROR]{C:\Sources\IoTHubAgent\externals\azure-iot-sdk-c\c-utility\adapters\socketio_win32.c:528}         Socketio_Failure: Receiving data from endpoint: 10054.
[13:55:08.820][ERROR]{C:\Sources\IoTHubAgent\externals\azure-iot-sdk-c\c-utility\src\wsio.c:448}                        on_underlying_ws_error called with error code 3
[13:55:09.330][ERROR]{C:\Sources\IoTHubAgent\externals\azure-iot-sdk-c\c-utility\src\tlsio_schannel.c:739}              [0x80090308]
[13:55:09.331][ERROR]{C:\Sources\IoTHubAgent\externals\azure-iot-sdk-c\c-utility\src\wsio.c:150}                        wsio_close when not open.
```
I use the last tag `2017-12-14`.
This happens only when connecting through a proxy.

It may be the same problem as the https://github.com/Azure/azure-iot-sdk-c/issues/264 issue I wrote for the Linux tlsio.

**Comment by tameraw** [comment]
@alexmrtn - We fixed some issues related to MQTT over websockets and are part of our latest release. Did this happen again on your end with the latest release?

**Comment by alexmrtn** [comment]
Hi @tameraw , unfortunately this problem is still there on the 2018-01-12 release.

**Comment by tameraw** [comment]
@alexmrtn thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
